import unittest
from HTMLTestRunner import HTMLTestRunner
import datetime
from testcase import TestSendCode,TestAccount,TestRegister,TestToken,TestHome

if __name__ =='__main__':
    
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestAccount.TestAccount))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestSendCode.TestSendCode))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestRegister.TestRegister))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestToken.TestToken))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestHome.TestHome))
    TextReport='TextReport'+ datetime.datetime.now().strftime('%Y%m%d%H%M%S')+'.html' 
    with open(TextReport,'wb') as f:
        runner = HTMLTestRunner(stream=f,title='MathFunc Test Report',description='generated by HTMLTestRunner.',verbosity=2)
        runner.run(suite) 
    # runner = unittest.TextTestRunner(verbosity=2)
    # runner.run(suite)